language: c
script: bash -ex .travis-ci.sh
sudo: required
before_install:
  - sudo add-apt-repository ppa:avsm/ppa:ppa=avsm/ocaml43+opam12 -y
  - sudo apt-get update -qq
  - sudo apt-get install ocaml ocaml-native-compilers camlp4-extra opam -qq